### ISSUE TITLE
make run sets the bigtable-autoscaler container's GOOGLE_APPLICATION_CREDENTIALS to a path in the host

### ISSUE THREAD

**Issue by AdamBSteele** [spotify/bigtable-autoscaler#112]
`make run` runs the bigtable-autoscaler container with `docker run --env-file=.env ... `

In the above command, the Docker container gets the value of `GOOGLE_APPLICATION_CREDENTIALS` from the `.env` file. However,  `GOOGLE_APPLICATION_CREDENTIALS` in `.env` points to a credentials file on your host machine.  The Docker container can't access that file, so an error is thrown when trying to authenticate with GCP.

` java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/home/adam/adams_creds.json': File does not exist.`

**Comment by goldfishy** [comment]
Thank you for fixing this! 

Closing the issue as the PR is merged.
