### ISSUE TITLE
Upgrade google-cloud-monitoring version

### ISSUE THREAD

**Issue by borislopezaraoz** [spotify/bigtable-autoscaler#23]
We are using a really old version (2017 and beta):

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-monitoring</artifactId>
            <version>0.32.0-beta</version>
        </dependency>

Latest is 1.76.0 (2019):
https://mvnrepository.com/artifact/com.google.cloud/google-cloud-monitoring

**Comment by bobo** [comment]
Fixed
