### ISSUE TITLE
Syntax error and table creation error in schema.sql

### ISSUE THREAD

**Issue by fadimki** [spotify/bigtable-autoscaler#36]
In resources/schema.sql you have following

```
SELECT INTO cluster_count COUNT(*)
FROM autoscale
WHERE enabled = true;
```
There are two issues with this statement. Assuming this is PostgreSQL, the syntax is invalid, should be:

``SELECT COUNT(*) INTO cluster_count``

Also after the first execution, this will only create errors as the table **cluster_count** already exists. You could simply just include the creation of this table at the top and do a normal insertion inside the trigger.

**Comment by borislopezaraoz** [comment]
Fix merged
Thanks @fadimki and @nputnam
