### ISSUE TITLE
Wrong java entrypoint into bigtable-autoscaler

### ISSUE THREAD

**Issue by VitaliShulhach** [spotify/bigtable-autoscaler#64]
Hi, 
At https://github.com/spotify/bigtable-autoscaler/blob/master/Dockerfile#L3, in '/usr/bin/java' string - the wrong place of Java binary. 

there is no such simlink in the source image (openjdk:11-jre), so java cannot start.

to fix that is enough to change to 'ENTRYPOINT [ "java", "-cp"'...

**Comment by bobo** [comment]
Thank you for pointing this out!

**Comment by goldfishy** [comment]
This has been fixed in [PR 108](https://github.com/spotify/bigtable-autoscaler/pull/108).
